version: '2'
services:
    cavmgr-app:
        image: cavmgr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cavmgr-mysql:3306/cavmgr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cavmgr-mysql:
        extends:
            file: mysql.yml
            service: cavmgr-mysql
